### ISSUE TITLE
Leaked globals name and sublabel

### ISSUE THREAD

**Issue by Voopie** [Dathwada/handynotes-covenant-sanctum#1]
Same as https://github.com/Dathwada/handynotes-oribos/issues/2

Leaked globals **name** and **sublabel** 

https://github.com/Dathwada/handynotes-covenant-sanctum/blob/fd8beb12ec71717e28fb0ac7b169c0e55023af57/core/handler.lua#L36-L37

global **name** is used in Blizzard_PVPUI/Blizzard_PVPUI.lua:1552 so it might lead to something bad ^-^

**Comment by Dathwada** [comment]
Thanks for the report.
They are now local variables.
